### PR TITLE
Update laminas-dependency-plugin

### LINKED ISSUE #2: Composer 2.0 Support
Maybe someone can update `laminas/laminas-dependency-plugin` dependency to `https://github.com/laminas/laminas-dependency-plugin/releases/tag/2.0.0beta1`? It just adds composer 2.0 support.

### PR DESCRIPTION
**Pull request by FabianKoestring**
Fix #2

### CODE REVIEW

**Comment by FabianKoestring** [comment]
Is there a way to merge this? It keeps us from updating to composer2.0. 🤯

**Comment by visto9259** [comment]
I am waiting for the plugin to be released.  It is still in beta.
I do not want to impose on all the users of this library to use the beta version of a dependency.
I can however make a branch just for this if you want.

**Comment by FabianKoestring** [comment]
> I am waiting for the plugin to be released. It is still in beta.
> I do not want to impose on all the users of this library to use the beta version of a dependency.
> I can however make a branch just for this if you want.

It is released 20 minutes ago ...
https://github.com/laminas/laminas-dependency-plugin/releases/tag/2.0.0

**Comment by visto9259** [comment]
OK.  Good.  Will look at it tonight (New York Time).  Did you update your pull request to have version 2 of the plugin?

**Comment by visto9259** [comment]
Released as 3.1.0 using a different pull request.
Thanks

**Pull request closed without merging**
